// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.22.0
// 	protoc        v3.12.3
// source: github.com/improbable-io/go-proto-logfields/logfields.proto

package logfields

import (
	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type LogField struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Prefix string `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
}

func (x *LogField) Reset() {
	*x = LogField{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_improbable_io_go_proto_logfields_logfields_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogField) ProtoMessage() {}

func (x *LogField) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_improbable_io_go_proto_logfields_logfields_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogField.ProtoReflect.Descriptor instead.
func (*LogField) Descriptor() ([]byte, []int) {
	return file_github_com_improbable_io_go_proto_logfields_logfields_proto_rawDescGZIP(), []int{0}
}

func (x *LogField) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LogField) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

var file_github_com_improbable_io_go_proto_logfields_logfields_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptor.FieldOptions)(nil),
		ExtensionType: (*LogField)(nil),
		Field:         62132,
		Name:          "improbable.logfield",
		Tag:           "bytes,62132,opt,name=logfield",
		Filename:      "github.com/improbable-io/go-proto-logfields/logfields.proto",
	},
	{
		ExtendedType:  (*descriptor.OneofOptions)(nil),
		ExtensionType: (*LogField)(nil),
		Field:         62133,
		Name:          "improbable.prefix",
		Tag:           "bytes,62133,opt,name=prefix",
		Filename:      "github.com/improbable-io/go-proto-logfields/logfields.proto",
	},
}

// Extension fields to descriptor.FieldOptions.
var (
	// optional improbable.LogField logfield = 62132;
	E_Logfield = &file_github_com_improbable_io_go_proto_logfields_logfields_proto_extTypes[0]
)

// Extension fields to descriptor.OneofOptions.
var (
	// optional improbable.LogField prefix = 62133;
	E_Prefix = &file_github_com_improbable_io_go_proto_logfields_logfields_proto_extTypes[1]
)

var File_github_com_improbable_io_go_proto_logfields_logfields_proto protoreflect.FileDescriptor

var file_github_com_improbable_io_go_proto_logfields_logfields_proto_rawDesc = []byte{
	0x0a, 0x3b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x6d, 0x70,
	0x72, 0x6f, 0x62, 0x61, 0x62, 0x6c, 0x65, 0x2d, 0x69, 0x6f, 0x2f, 0x67, 0x6f, 0x2d, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2d, 0x6c, 0x6f, 0x67, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x2f, 0x6c, 0x6f,
	0x67, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x69,
	0x6d, 0x70, 0x72, 0x6f, 0x62, 0x61, 0x62, 0x6c, 0x65, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x36, 0x0a, 0x08, 0x4c,
	0x6f, 0x67, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x70,
	0x72, 0x65, 0x66, 0x69, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x72, 0x65,
	0x66, 0x69, 0x78, 0x3a, 0x51, 0x0a, 0x08, 0x6c, 0x6f, 0x67, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x12,
	0x1d, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xb4,
	0xe5, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x69, 0x6d, 0x70, 0x72, 0x6f, 0x62, 0x61,
	0x62, 0x6c, 0x65, 0x2e, 0x4c, 0x6f, 0x67, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x08, 0x6c, 0x6f,
	0x67, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x3a, 0x4d, 0x0a, 0x06, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78,
	0x12, 0x1d, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x4f, 0x6e, 0x65, 0x6f, 0x66, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18,
	0xb5, 0xe5, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x69, 0x6d, 0x70, 0x72, 0x6f, 0x62,
	0x61, 0x62, 0x6c, 0x65, 0x2e, 0x4c, 0x6f, 0x67, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x06, 0x70,
	0x72, 0x65, 0x66, 0x69, 0x78, 0x42, 0x37, 0x5a, 0x35, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x6d, 0x70, 0x72, 0x6f, 0x62, 0x61, 0x62, 0x6c, 0x65, 0x2d, 0x69,
	0x6f, 0x2f, 0x67, 0x6f, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x6c, 0x6f, 0x67, 0x66, 0x69,
	0x65, 0x6c, 0x64, 0x73, 0x3b, 0x6c, 0x6f, 0x67, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_github_com_improbable_io_go_proto_logfields_logfields_proto_rawDescOnce sync.Once
	file_github_com_improbable_io_go_proto_logfields_logfields_proto_rawDescData = file_github_com_improbable_io_go_proto_logfields_logfields_proto_rawDesc
)

func file_github_com_improbable_io_go_proto_logfields_logfields_proto_rawDescGZIP() []byte {
	file_github_com_improbable_io_go_proto_logfields_logfields_proto_rawDescOnce.Do(func() {
		file_github_com_improbable_io_go_proto_logfields_logfields_proto_rawDescData = protoimpl.X.CompressGZIP(file_github_com_improbable_io_go_proto_logfields_logfields_proto_rawDescData)
	})
	return file_github_com_improbable_io_go_proto_logfields_logfields_proto_rawDescData
}

var file_github_com_improbable_io_go_proto_logfields_logfields_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_github_com_improbable_io_go_proto_logfields_logfields_proto_goTypes = []interface{}{
	(*LogField)(nil),                // 0: improbable.LogField
	(*descriptor.FieldOptions)(nil), // 1: google.protobuf.FieldOptions
	(*descriptor.OneofOptions)(nil), // 2: google.protobuf.OneofOptions
}
var file_github_com_improbable_io_go_proto_logfields_logfields_proto_depIdxs = []int32{
	1, // 0: improbable.logfield:extendee -> google.protobuf.FieldOptions
	2, // 1: improbable.prefix:extendee -> google.protobuf.OneofOptions
	0, // 2: improbable.logfield:type_name -> improbable.LogField
	0, // 3: improbable.prefix:type_name -> improbable.LogField
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	2, // [2:4] is the sub-list for extension type_name
	0, // [0:2] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_github_com_improbable_io_go_proto_logfields_logfields_proto_init() }
func file_github_com_improbable_io_go_proto_logfields_logfields_proto_init() {
	if File_github_com_improbable_io_go_proto_logfields_logfields_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_github_com_improbable_io_go_proto_logfields_logfields_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogField); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_github_com_improbable_io_go_proto_logfields_logfields_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_github_com_improbable_io_go_proto_logfields_logfields_proto_goTypes,
		DependencyIndexes: file_github_com_improbable_io_go_proto_logfields_logfields_proto_depIdxs,
		MessageInfos:      file_github_com_improbable_io_go_proto_logfields_logfields_proto_msgTypes,
		ExtensionInfos:    file_github_com_improbable_io_go_proto_logfields_logfields_proto_extTypes,
	}.Build()
	File_github_com_improbable_io_go_proto_logfields_logfields_proto = out.File
	file_github_com_improbable_io_go_proto_logfields_logfields_proto_rawDesc = nil
	file_github_com_improbable_io_go_proto_logfields_logfields_proto_goTypes = nil
	file_github_com_improbable_io_go_proto_logfields_logfields_proto_depIdxs = nil
}
